/* autogenerated by Processing revision 1293 on 2024-05-16 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import controlP5.*;
import ch.bildspur.artnet.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Artnet_Visualizer extends PApplet {




ArtNetClient artnet;
ControlP5 cp5;

public void setup()
{
  //window setup
  /* size commented out by preprocessor */;
  textAlign(LEFT, TOP);
  textSize(20); 
  
  //CP5 stuff
  PFont font = createFont("arial",30);
  cp5 = new ControlP5(this);
  cp5.addTextfield("")
    .setPosition(10,10)
    .setSize(35,35)
    .setFont(font);
  cp5.addButton("set universe")
    .setPosition(46,10)
    .setSize(75,35);
  
  // create artnet client
  artnet = new ArtNetClient();
  artnet.start();
}

int universe = 0;
int warningCountDown = 0;

public void draw()
{
  // read rgb color from the first 3 bytes
  byte[] data = artnet.readDmxData(0, universe);
  
  int c = color(data[0] & 0xFF, data[1] & 0xFF, data[2] & 0xFF);

  // set background
  background(color(200,200,200));
  
  
  for (int i = 0; i<512; i+=4)
  {
    //println(data[i] & 0xFF);
    fill(data[i] & 0xFF, data[i+1] & 0xFF, data[i+2] & 0xFF);
    stroke(data[i] & 0xFF, data[i+1] & 0xFF, data[i+2] & 0xFF);
    square(50+50*(PApplet.parseInt(i/4)-PApplet.parseInt(i/64)*16),50+50*PApplet.parseInt(i/64),50);
  }
  
  //show warning message for unvierse setting:
  if (warningCountDown>0)
  {
    text("Please make sure you have a valid number in the textbox!",130,20);
    warningCountDown--;
  }

  // show values
//  text("R: " + (int)red(c) + " Green: " + (int)green(c) + " Blue: " + (int)blue(c), width / 2, height / 2);
}



//universe changing logic
int boxUniverse = 0;
public void controlEvent(ControlEvent e) {
  if(e.isAssignableFrom(Button.class)) {
    String text = cp5.get(Textfield.class, "").getText();
    println(text);
    try 
    {
      universe = Integer.parseInt(text);
      warningCountDown = 0;
    } 
    catch(Exception ex)
    {
      warningCountDown = 180;
    }
  }
}


  public void settings() { size(1280, 720); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Artnet_Visualizer" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
